### ISSUE TITLE
https://github.com/ag-grid/ag-grid/issues/5286

### ISSUE THREAD

**Issue by haomashroom** [andyFang94/react-antd-cron#5]
那个ag-grid的这个问题你解决了吗

**Comment by andyFang94** [comment]
> 那个ag-grid的这个问题你解决了吗
hi，没有及时看到消息
没有去仔细处理，不过我想到了解决的思路
1.表格cell渲染的组件  双击事件拦截判断   或者 重写cell 渲染组件，组件内部拦截双击事件
2.双击后获取正在编辑的cell  进行判断是否放行
